3 module
js-tasks-ru/jsbasic-20210621_sazx85 pull request #4
Opened 2021-07-06 20:14 UTC by sazx85

2021-07-06 20:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-07 16:46 UTC, SinimaWath requested changes

2021-07-07 16:46 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return arr.join("");
Молодец что так сделал. Но давай попробуем через split->map->join

2021-07-07 16:46 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return str.join("\n");
Давай это тоже для практики попробуем через: filter->map->join

2021-07-07 18:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-09 15:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-09 16:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-09 18:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-10 15:55 UTC, SinimaWath requested changes

2021-07-10 15:55 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
- Давай используем стрелочную функцию, так будет понятней
- если не используешь аргументы index, array, не нужно их обьявлять

2021-07-10 15:55 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  let result = arr.map(function(item, index, array) {
- Тут тоже давай стрелочную
- И если не используешь array, то не стоит обьявлять

2021-07-12 06:42 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-13 13:01 UTC, SinimaWath approved these changes
Все круто )

2021-07-13 13:02 UTC, merged