6th module
js-tasks-ru/jsbasic-20210621_sazx85 pull request #6
Opened 2021-07-21 14:44 UTC by sazx85

2021-07-21 14:47 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-21 15:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-21 17:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-22 11:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-22 16:00 UTC, SinimaWath requested changes

2021-07-22 16:00 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    let m = this._rows;
Непонятное название переменной, зачем она нужна?

2021-07-22 16:00 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    button.innerHTML = 'X';
Давай все таки через шаблон создадим, через него будет понятней из чего состоит твоя кнопка

2021-07-22 16:00 UTC, SinimaWath commented on 6-module/2-task/index.js
> +                      </div>`;
Давай использовать createElement хелпер с первой строчки:
```
createElement(`
<div class="card">
  <div class="card__top">
  </div>
</div>
`)
```

2021-07-22 16:00 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    this.carouselInner.style.transform = `translateX(-${this.currentOffset}px)`;
Давай логику translate - вынесем в отдельный метод, который можно будет переиспользовать

2021-07-22 20:06 UTC, sazx85 commented on 6-module/1-task/index.js
> +    let m = this._rows;
Посмотрел еще раз на код и тоже понял, что она не нужна. Убрал

2021-07-22 20:06 UTC, sazx85 commented on 6-module/1-task/index.js
> +    button.innerHTML = 'X';
Сделал

2021-07-22 20:06 UTC, sazx85 commented on 6-module/2-task/index.js
> +                      </div>`;
Сделал

2021-07-22 20:06 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-22 20:07 UTC, sazx85 commented on 6-module/3-task/index.js
> +    this.carouselInner.style.transform = `translateX(-${this.currentOffset}px)`;
Вынес в _translateSlides()

2021-07-23 13:14 UTC, SinimaWath approved these changes
все круто!

2021-07-23 13:15 UTC, merged