Homework
js-tasks-ru/jsbasic-20210621_sazx85 pull request #7
Opened 2021-07-23 14:16 UTC by sazx85

2021-07-23 14:17 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-23 15:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-24 15:23 UTC, SinimaWath requested changes

2021-07-24 15:23 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    this.title = title;
setTitle - должно изменять DOM-елемент модалки

2021-07-24 15:23 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    document.addEventListener('keydown', function(event) {
после того как закрыли модалку, нужно от события отписаться. 

Иначе каждый вызов метода open - создается новый обработчик события, а старый не удаляет

2021-07-24 15:23 UTC, SinimaWath commented on 7-module/2-task/index.js
> +        document.body.querySelector('.modal').remove();
У тебя такой же код в `close`, давай переиспользуем: `this.close()`

2021-07-24 15:23 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    this.body = body;
setBody - должен изменять DOM-елемент

2021-07-27 09:35 UTC, sazx85 commented on 7-module/2-task/index.js
> +        document.body.querySelector('.modal').remove();
у меня не работает this.close() в этом месте. Не понимаю, как ее туда поместить

2021-07-27 10:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-27 10:45 UTC, sazx85 commented on 7-module/2-task/index.js
> +    this.body = body;
Поправил. Но тесты все равно не падают, хотя все работает как нужно и в консоль не бросает ошибок

2021-07-27 10:45 UTC, sazx85 commented on 7-module/2-task/index.js
> +        document.body.querySelector('.modal').remove();
Разобрался. Поправил. Но тесты все равно не падают, хотя все работает как нужно и в консоль не бросает ошибок

2021-07-27 10:45 UTC, sazx85 commented on 7-module/2-task/index.js
> +    document.addEventListener('keydown', function(event) {
Поправил. Но тесты все равно не падают, хотя все работает как нужно и в консоль не бросает ошибок

2021-07-27 10:45 UTC, sazx85 commented on 7-module/2-task/index.js
> +    this.title = title;
Поправил. Но тесты все равно не падают, хотя все работает как нужно и в консоль не бросает ошибок

2021-07-27 11:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-27 12:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-28 13:20 UTC, sazx85 commented on 7-module/2-task/index.js
> +    this.title = title;
Разобрался с тестами. Теперь ничего не падает

2021-07-28 13:20 UTC, sazx85 commented on 7-module/2-task/index.js
> +    document.addEventListener('keydown', function(event) {
Разобрался с тестами. Теперь ничего не падает

2021-07-28 13:20 UTC, sazx85 commented on 7-module/2-task/index.js
> +        document.body.querySelector('.modal').remove();
Разобрался с тестами. Теперь ничего не падает

2021-07-28 13:20 UTC, sazx85 commented on 7-module/2-task/index.js
> +    this.body = body;
Разобрался с тестами. Теперь ничего не падает

2021-07-28 13:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-28 15:41 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-29 10:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-29 16:42 UTC, SinimaWath approved these changes

2021-07-29 16:43 UTC, merged